#
# Sample 'icecast' driver configuration file.
#
---
port: 9000
# Icecast driver.
driver: icecast
icecast:
  rtl_fm: /usr/local/bin/rtl_fm
  sox: /usr/local/bin/sox
  ffmpeg: /usr/local/bin/ffmpeg
  icecast_url: http://source:hackme@localhost:8080/radio
