#
# Sample 'native' driver configuration file.
# 
---
port: 9000
# Auth settings
#
# Valid auth types: 'basic' and 'none' (omitting the 'auth' field is the same
# as an 'auth' field of 'none'.
#
# Uncomment to require auth to change the frequency.
# auth:
#   type: basic
#   # This indicates whether 'readonly' (GET) requests require auth or not.
#   ignore_on_read: true
#   # Each user is denoted by: <user>: <password>
#   users:
#     admin: admin

# Starting (FM) channel/frequency to listen on startup.
default_frequency: 107.3M
# Driver settings.
driver:
  type: native
  rtl_fm: /usr/local/bin/rtl_fm
  # Optional.
  kb_buffer_size: 128
